#!/bin/sh -e

if [ -z ${MITTOS64+x} ]; then >&2 echo "Unsupported environment! See README"; exit 1; fi

iso=${BUILDROOT}mittos64.iso

${BUILDROOT}toolchain/mkiso

qemu-system-x86_64 -s -S -cdrom ${iso} -curses
