#!/bin/sh -e

if [ -z ${MITTOS64+x} ]; then >&2 echo "Unsupported environment! See README"; exit 1; fi

sysroot=/opt/sysroot
iso=/opt/mittos64.iso

mkdir -p ${sysroot}

grub-mkrescue -o ${iso} ${sysroot}
